### PR TITLE
Update array.md

### PR DESCRIPTION
**Pull request by shivan-s**
adding (num) for the map in the docs.

I think the commit and PR are self-explanatory. I hope this helps.

Apologies if this bypasses the rules of collaboration but wanted to make this simple.

### CODE REVIEW

**Comment by crutchcorn** [comment]
Oh! Thank you for catching this!

**Comment by crutchcorn** [comment]
@all-contributors, please add @shivan-s for docs

**Review by crutchcorn — APPROVED** [review]

**Comment by crutchcorn** [comment]
@allcontributors please add @shivan-s for docs

**Comment by shivan-s** [comment]
> Oh! Thank you for catching this!

The pleasure is mine. :)

**Pull request merged**
